name: test-and-deploy

on:
  push:
    branches:
      - main  # Adjust this branch name based on your setup

jobs:
  test:
    runs-on: ubuntu-latest  # Correct the key from "run-on" to "runs-on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2  # Updated from "v4" to "v2"
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: python -m pytest ./tests
